name: Serverless Video Transcoder Service CI/CD

env:
  AWS_REGION: "us-east-1"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
        
      - name: Install dependencies
        run: npm ci
      
      - name: Install CDK
        run: npm install -g aws-cdk
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::576546092487:role/actions-assume-role
          role-session-name: Github_Actions_Role_OIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Run Test
        run: npm test
      
      - name: CDK Synth
        run: cdk synth
      
      - name: CDK Deploy
        run: cdk deploy --require-approval never
